spring:
  application:
    name: order-platform
  datasource:
#    url: ${DB_URL}
    url: jdbc:postgresql://${DB_URL}/orderflow?currentSchema=${POSTGRES_SCHEMA:public}, public
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:10}
      connection-timeout: 5000
      connection-init-sql: "SET lock_timeout = '5s'; SET statement_timeout = '30s'"
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  data:
    web:
      pageable:
        max-page-size: 100
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      connect-timeout: 1s
      timeout: 1s
server:
  shutdown: graceful
  error:
    include-message: never
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      validate-group-membership: false
      probes:
        enabled: true
      show-details: never
      group:
        readiness:
          include: readinessState,db,redis
        liveness:
          include: livenessState
  health:
    redis:
      enabled: ${REDIS_ENABLED:false}
app:
  jwt:
    secret: ${JWT_SECRET}
    issuer: order-platform
    ttl: PT30M
  tax-rate: ${TAX_RATE:0.18}
  redis-enabled: ${REDIS_ENABLED:false}
  payment:
    poll-ms: 3000
    reservation-ttl: PT15M
#logging:
#  structured:
#    format:
#      console: logstash
springdoc:
  use-fqn: true
  swagger-ui:
    path: /swagger-ui.html
